### ISSUE TITLE
UnicodeEncodeError for Unicode input

### ISSUE THREAD

**Issue by deeplook** [danmichaelo/mwtemplates#4]
I'm trying to parse content like this: https://en.wikipedia.org/w/index.php?title=Template:Infobox_titanium&action=edit but am getting Unicode issues, which I'm illustrating with this abbreviated example below. Passing the input encoded to UTF-8 (with ``TemplateEditor(infobox_sample_non_ascii.encode('utf-8')``) doesn't work either. I'm trying mwtemplates 0.3.4 on Python 2.7.

Notice also the ``No handlers could be found for logger "root"`` warning on line 3.

```
In [1]: from mwtemplates import TemplateEditor

In [2]: infobox_sample_non_ascii = u"""
   ...: {{infobox element
   ...: |number=22
   ...: |name=titanium
   ...: |first isolation by=[[Jöns Jakob Berzelius]]
   ...: }}
   ...: """

In [3]: te = TemplateEditor(infobox_sample_non_ascii)
No handlers could be found for logger "root"

In [4]: ie = te.templates['Infobox element']

In [5]: ie0 = ie[0]

In [6]: ie0.parameters
Out[6]: <repr(<mwtemplates.templateeditor2.Parameters at 0x102ce47d0>) failed: UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 66: ordinal not in range(128)>
```

**Comment by danmichaelo** [comment]
The internal representation is ok, you can still work with the parameters:

```
In [16]: ie0.parameters.keys()
Out[16]: [u'number', u'name', u'first isolation by']

In [19]: ie0.parameters['first isolation by'].value
Out[19]: u'[[J\xf6ns Jakob Berzelius]]'
```

But I need to fix the `__repr__` method!

**Comment by danmichaelo** [comment]
`No handlers could be found for logger "root"` is harmless, but I can add the same fix as added here: https://github.com/mwclient/mwclient/issues/82

**Comment by danmichaelo** [comment]
Both issues should be fixed now.

**Comment by deeplook** [comment]
Thanks!
