### ISSUE TITLE
Use for inline data templates?

### ISSUE THREAD

**Issue by rexdouglass** [danmichaelo/mwtemplates#7]
I've already parsed infoboxes using mwparserfromhell from the english xml dump. Many of the values contain inline wikidata templates, e.g. {{flagcountry|ITA}} , {{Birth date|1993|2|4|df=yes}}.

I haven't found a dataset of the templates yet, just wikipedia descriptions and these kinds of descriptions
https://en.wikipedia.org/w/index.php?title=Template:Flagcountry&action=edit

Does this tool handle those, and if so can you give a brief example of how I could automate the processes?

**Comment by danmichaelo** [comment]
It does handle inline templates well, yes. That's actually largely why I made it.

I don't understand what you try to do though from what you've written so far though. Please explain a little more.

**Comment by rexdouglass** [comment]
Excellent. Thanks for the feedback, there is a great deal of specialized knowledge in these systems and I'm on the beginning end of the curve.

I'd be able to pass the text "{{Birth date|1993|2|4|df=yes}}" to your package (or some other code), and return a dictionary or json or list, with the correct key-value pairs.
Following the template here https://en.wikipedia.org/wiki/Template:Birth_date
"{{Birth date|1993|2|4|df=yes}}" should turn into
'Year of birth'='1993'
'Month of birth'='2'
'Day of birth'='4'
'Day first'='yes'

That would be ideal. Baring that, I'd settle for just being translated to raw text correctly ''4 February, 1993" which I can then parse as a date.

I'm doing this for all templates that contain usable information in wikipedia. So far my hurdles are that I have not found an easy way to download their formats in one single place to write my own parser, and there are literally thousands of them with I'm sure edge cases and I'm not eager to write my own parser from scratch.

**Comment by danmichaelo** [comment]
mwtemplates should be work well for that use case. Here's something that should get you started:

```python
from mwtemplates import TemplateEditor

parameter_map = {
    1: 'Year of birth',
    2: 'Month of birth',
    3: 'Day of birth',
    'df': 'Day first',
}

te = TemplateEditor('{{Birth date|1993|2|4|df=yes}}')
if 'Birth date' in te.templates:
    tpl = te.templates['Birth date'][0]  # to get the first template in the text
    print(tpl.parameters.items())  # for testing
    # extract the parameters you want:
    params =  {v: tpl.parameters.get(k) for k, v in parameter_map.items()}
    print(params)
```

**Comment by rexdouglass** [comment]
Thank you very much for the answer, code example, and especially thoughtful warnings about comments and other oddities.

I think this it out of the scope of the package, but do you know of any way to automatically derive that parameter map. Defining it by hand is precisely what I'm trying to avoid. There are thousands of them, and they're easy to get wrong.

I haven't found a machine readable definition of them all in one place yet. All I can find is these human readable pages, e.g. https://en.wikipedia.org/wiki/Template:Birth_date

**Comment by danmichaelo** [comment]
Not really, but many templates now have TemplateData that can help you a bit:

https://en.wikipedia.org/wiki/Template:Birth_date_and_age/doc#TemplateData

You could even try to write a script that creates a map from the TemplateData JSON, but I'm quite sure you still would have to manually inspect it and ensure it's sane :)

**Comment by danmichaelo** [comment]
Btw. I'm closing the issue, but feel free to continue the discussion if anything is unclear. I should probably have made a Gitter room or something.

**Comment by rexdouglass** [comment]
Thanks much for the help. I've now scraped some 2,000 TemplateData tables from the html, but many templates don't have one and there's variation among the one's I've scraped. This seems like the kind of thing that would be integral for wikimedia to make machine readable. Otherwise something like 20% of infobox properties are locked in formats only readable by random lua scripts in an extension. Weird! =)

**Comment by danmichaelo** [comment]
The dream is that everything will be migrated to Wikidata and fetched from there, but it's still mostly a dream. At some of the "smaller" wikipedias, like Norwegian Bokmål Wikipedia, we experiment with it, see e.g. https://no.wikipedia.org/wiki/Viorica_D%C4%83ncil%C4%83 were all the infobox parameters are fetched from Wikidata. But for some of the more complex boxes, it's, well, complex, both to find the best way to represent the data at Wikidata, and to extract and present it. And at English Wikipedia there seems to be a lot of opposition to the whole idea.

**Comment by rexdouglass** [comment]
That's fascinating. My group at UCSD is working on this problem, but from the social science community side of things. It would be very interesting to plug into the wiki-community/cs side and see the technical/political debates.

**Comment by danmichaelo** [comment]
It is fascinating, yes. I haven't followed the debates closely, but this Signpost report gives you an impression:  https://en.wikipedia.org/wiki/Wikipedia:Wikipedia_Signpost/2015-06-03/Discussion_report#Wikidata_gadget . I'm sure you can reach out to the Wikidata team or to https://en.wikipedia.org/wiki/Wikipedia:Research if you want to dive deeper into it.
